version: "3"
services:
  mysql:
    container_name: zhx-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=litblc
      - MYSQL_PASSWORD=EGzsj2021^^
    ports:
      - "13306:3306"
    expose:
      - "3306"
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      #- ./docker/mysql/etc/my.cnf:/etc/mysql/my.cnf
    networks:
      - lnmp

  redis:
    container_name: zhx-redis
    image: redis:5.0
    ports:
      - "16379:6379"
    expose:
      - "6379"
    volumes:
      - ./docker/redis/etc/6379.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
      - ./docker/redis/log:/logs
    restart: always #重启
    networks:
      - lnmp

  php:
    container_name: zhx-php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    expose:
      - "9000"
    environment:
      - TZ=Asia/Shanghai      
    links:
      - mysql
      - redis
    restart: always
    networks:
      - lnmp
    volumes:
      - ./docker/php/etc/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/logs/:/var/log/php
      - ./www:/data/www

  nginx:
    container_name: zhx-nginx
    image: nginx:1.21
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/log/:/var/log/nginx
      - ./www:/data/www
    ports:
      - "9527:80"
      - "9443:443"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    links:
      - php
    depends_on:
      - mysql
      - redis
      - php
    networks:
      - lnmp

networks:
  lnmp:
    driver: bridge